/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthCallbackProviderImport } from './routes/auth/callback.$provider'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackProviderRoute = AuthCallbackProviderImport.update({
  id: '/auth/callback/$provider',
  path: '/auth/callback/$provider',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/callback/$provider': {
      id: '/auth/callback/$provider'
      path: '/auth/callback/$provider'
      fullPath: '/auth/callback/$provider'
      preLoaderRoute: typeof AuthCallbackProviderImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/callback/$provider'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/callback/$provider'
  id: '__root__' | '/' | '/auth/callback/$provider'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackProviderRoute: typeof AuthCallbackProviderRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackProviderRoute: AuthCallbackProviderRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/callback/$provider"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/callback/$provider": {
      "filePath": "auth/callback.$provider.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
